In [196]:
import sys

print(sys.version)


print("All packages imported successfully!")

3.11.16 (main, Sep  1 2026, 14:15:24) [MSC v.1944 64 bit (AMD64)]
All packages imported successfully!

In [197]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import xgboost

print("All packages imported successfully!")

All packages imported successfully!

In [198]:
import pandas as pd

sku_master = pd.read_csv("../data/raw/sku_master.csv")
sales_daily = pd.read_csv("../data/raw/sales_daily.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")
inventory = pd.read_csv("../data/raw/inventory_snapshots.csv")

In [199]:
sku_master.head()

,SKU,Product_Name,Category,Subcategory,Launch_Date,Cost_Price,Selling_Price,Gross_Margin_Per_Unit
0,SKU001,Product 001,Furniture,Chair,2022-04-09,1758.45,3664.05,1905.60
1,SKU002,Product 002,Home Decor,Table,2024-05-01,3867.09,3805.69,-61.40
2,SKU003,Product 003,Kitchen,Cushion,2023-12-22,589.48,8078.23,7488.75
3,SKU004,Product 004,Lighting,Cookware,2023-04-28,1445.74,6861.57,5415.83
4,SKU005,Product 005,Storage,Lamp,2023-04-22,5543.63,9493.22,3949.59

In [200]:
print(sales_daily.head())

         Date     SKU  Units_Sold    Revenue    Price  Promotion
0  2024-01-01  SKU001           5   18320.25  3664.05          0
1  2024-01-01  SKU002          15   57085.35  3805.69          0
2  2024-01-01  SKU003           5   40391.15  8078.23          0
3  2024-01-01  SKU004           5   34307.85  6861.57          0
4  2024-01-01  SKU005          12  113918.64  9493.22          0

In [201]:
calendar.head()

,date,year,month,quarter,week,day_of_week,is_weekend,season,holiday,is_holiday,promotion_event
0,2024-01-01,2024,1,Q1,1,Monday,0,Winter,NaN,0,NaN
1,2024-01-02,2024,1,Q1,1,Tuesday,0,Winter,NaN,0,NaN
2,2024-01-03,2024,1,Q1,1,Wednesday,0,Winter,NaN,0,NaN
3,2024-01-04,2024,1,Q1,1,Thursday,0,Winter,NaN,0,NaN
4,2024-01-05,2024,1,Q1,1,Friday,0,Winter,NaN,0,NaN

In [202]:
inventory.head()

,Snapshot_Date,SKU,Current_Stock,On_Order,Lead_Time_Days,Safety_Stock,Reorder_Point,Inventory_Value
0,2024-01-01,SKU001,16,23,11,7,18,58420.96
1,2024-01-01,SKU002,29,12,4,5,10,163983.40
2,2024-01-01,SKU003,34,23,14,6,20,209060.22
3,2024-01-01,SKU004,34,4,7,5,12,42257.92
4,2024-01-01,SKU005,23,5,5,6,11,170945.89

In [203]:
print("sku_master shape:", sku_master.shape)
print("sales_daily shape:", sales_daily.shape)
print("calendar shape:", calendar.shape)
print("inventory shape:", inventory.shape)

sku_master shape: (50, 8)
sales_daily shape: (36550, 6)
calendar shape: (731, 11)
inventory shape: (4800, 8)

In [204]:
print("-----------------------sku_master info:-----------------------")
sku_master.info()
print("\n-----------------------sales_daily info:-----------------------")
sales_daily.info()
print("\n-----------------------calendar info:-----------------------")
calendar.info()
print("\n-----------------------inventory info:-----------------------")
inventory.info()

-----------------------sku_master info:-----------------------
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SKU                    50 non-null     str
 1   Product_Name           50 non-null     str
 2   Category               50 non-null     str
 3   Subcategory            50 non-null     str
 4   Launch_Date            50 non-null     str
 5   Cost_Price             50 non-null     float64
 6   Selling_Price          50 non-null     float64
 7   Gross_Margin_Per_Unit  50 non-null     float64
dtypes: float64(3), str(5)
memory usage: 3.3 KB

-----------------------sales_daily info:-----------------------
<class 'pandas.DataFrame'>
RangeIndex: 36550 entries, 0 to 36549
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        36550 non-null  str
 1   SKU         36550 non-null  str
 2   Units_Sold  36550 non-null  int64
 3   Revenue     36550 non-null  float64
 4   Price       36550 non-null  float64
 5   Promotion   36550 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.7 MB

-----------------------calendar info:-----------------------
<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             731 non-null    str
 1   year             731 non-null    int64
 2   month            731 non-null    int64
 3   quarter          731 non-null    str
 4   week             731 non-null    int64
 5   day_of_week      731 non-null    str
 6   is_weekend       731 non-null    int64
 7   season           731 non-null    str
 8   holiday          8 non-null      str
 9   is_holiday       731 non-null    int64
 10  promotion_event  75 non-null     str
dtypes: int64(5), str(6)
memory usage: 62.9 KB

-----------------------inventory info:-----------------------
<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Snapshot_Date    4800 non-null   str
 1   SKU              4800 non-null   str
 2   Current_Stock    4800 non-null   int64
 3   On_Order         4800 non-null   int64
 4   Lead_Time_Days   4800 non-null   int64
 5   Safety_Stock     4800 non-null   int64
 6   Reorder_Point    4800 non-null   int64
 7   Inventory_Value  4800 non-null   float64
dtypes: float64(1), int64(5), str(2)
memory usage: 300.1 KB

In [205]:
print("------------Null Value Counts:--------------")
print("*********sku_master null values:**********")
print(sku_master.isnull().sum())
print("*********sales_daily null values:**********")
print(sales_daily.isnull().sum())
print("*********calendar null values:**********")
print(calendar.isnull().sum())
print("*********inventory null values:**********")
print(inventory.isnull().sum())

------------Null Value Counts:--------------
*********sku_master null values:**********
SKU                      0
Product_Name             0
Category                 0
Subcategory              0
Launch_Date              0
Cost_Price               0
Selling_Price            0
Gross_Margin_Per_Unit    0
dtype: int64
*********sales_daily null values:**********
Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64
*********calendar null values:**********
date                 0
year                 0
month                0
quarter              0
week                 0
day_of_week          0
is_weekend           0
season               0
holiday            723
is_holiday           0
promotion_event    656
dtype: int64
*********inventory null values:**********
Snapshot_Date      0
SKU                0
Current_Stock      0
On_Order           0
Lead_Time_Days     0
Safety_Stock       0
Reorder_Point      0
Inventory_Value    0
dtype: int64

## 2. Data Quality Checks

### Check sku_master

In [206]:
print("Shape:", sku_master.shape)

print("\nDuplicate SKUs:")
print(sku_master["SKU"].duplicated().sum())

print("\nNegative margins:")
display(
    sku_master[sku_master["Gross_Margin_Per_Unit"] < 0]
)

print("\nInvalid cost prices:")
display(
    sku_master[sku_master["Cost_Price"] <= 0]
)

print("\nInvalid selling prices:")
display(
    sku_master[sku_master["Selling_Price"] <= 0]
)

Shape: (50, 8)

Duplicate SKUs:
0

Negative margins:

,SKU,Product_Name,Category,Subcategory,Launch_Date,Cost_Price,Selling_Price,Gross_Margin_Per_Unit
1,SKU002,Product 002,Home Decor,Table,2024-05-01,3867.09,3805.69,-61.40
6,SKU007,Product 007,Home Decor,Cabinet,2022-04-05,7748.20,5114.09,-2634.11
8,SKU009,Product 009,Lighting,Organizer,2022-08-10,3121.06,2336.89,-784.17
9,SKU010,Product 010,Storage,Sofa,2022-04-14,3889.06,663.46,-3225.60
10,SKU011,Product 011,Furniture,Chair,2023-08-03,1718.40,1444.56,-273.84
15,SKU016,Product 016,Furniture,Shelf,2024-05-14,3637.93,2166.82,-1471.11
17,SKU018,Product 018,Kitchen,Rug,2022-05-21,5677.05,5575.41,-101.64
19,SKU020,Product 020,Storage,Sofa,2023-05-11,6700.01,3897.54,-2802.47
22,SKU023,Product 023,Kitchen,Cushion,2022-07-20,2484.54,1416.74,-1067.80
23,SKU024,Product 024,Lighting,Cookware,2024-10-16,5539.34,1768.87,-3770.47
27,SKU028,Product 028,Kitchen,Rug,2024-06-24,6348.66,3484.09,-2864.57
32,SKU033,Product 033,Kitchen,Cushion,2022-04-12,4657.74,3558.00,-1099.74
36,SKU037,Product 037,Home Decor,Cabinet,2024-08-02,3901.00,2747.42,-1153.58
37,SKU038,Product 038,Kitchen,Rug,2024-06-29,4630.58,3949.10,-681.48
39,SKU040,Product 040,Storage,Sofa,2023-11-26,5169.07,2450.56,-2718.51
47,SKU048,Product 048,Kitchen,Rug,2024-09-09,6863.87,1379.55,-5484.32

Invalid cost prices:

Empty DataFrame
Columns: [SKU, Product_Name, Category, Subcategory, Launch_Date, Cost_Price, Selling_Price, Gross_Margin_Per_Unit]
Index: []

Invalid selling prices:

Empty DataFrame
Columns: [SKU, Product_Name, Category, Subcategory, Launch_Date, Cost_Price, Selling_Price, Gross_Margin_Per_Unit]
Index: []

### Check Sales

In [207]:
print("Shape:", sales_daily.shape)

print("\nDuplicate Date + SKU combinations:")
print(
    sales_daily.duplicated(
        subset=["Date", "SKU"]
    ).sum()
)

print("\nUnits Sold summary:")
display(sales_daily["Units_Sold"].describe())

print("\nNegative Units Sold:")
display(
    sales_daily[sales_daily["Units_Sold"] < 0]
)


print("\nPromotion distribution:")
display(sales_daily["Promotion"].value_counts())

Shape: (36550, 6)

Duplicate Date + SKU combinations:
0

Units Sold summary:

count    36550.000000
mean        14.003010
std          8.467305
min          0.000000
25%          7.000000
50%         13.000000
75%         20.000000
max         56.000000
Name: Units_Sold, dtype: float64

Negative Units Sold:

Empty DataFrame
Columns: [Date, SKU, Units_Sold, Revenue, Price, Promotion]
Index: []

Promotion distribution:

Promotion
0    32800
1     3750
Name: count, dtype: int64

### Check Calender

In [208]:
print("Shape:", calendar.shape)

print("\nDuplicate dates:")
print(calendar["date"].duplicated().sum())


print("\nDate range:")
print(calendar["date"].min(), "to", calendar["date"].max())

print("\nWeekend distribution:")
display(calendar["is_weekend"].value_counts())

print("\nHoliday distribution:")
display(calendar["is_holiday"].value_counts())

Shape: (731, 11)

Duplicate dates:
0

Date range:
2024-01-01 to 2025-12-31

Weekend distribution:

is_weekend
0    523
1    208
Name: count, dtype: int64

Holiday distribution:

is_holiday
0    723
1      8
Name: count, dtype: int64

### Check inventory

In [209]:
print("Shape:", inventory.shape)

print("\nDuplicate SKU + Snapshot Date:")
print(
    inventory.duplicated(
        subset=["SKU", "Snapshot_Date"]
    ).sum()
)


print("\nNegative Current Stock:")
display(
    inventory[inventory["Current_Stock"] < 0]
)

print("\nNegative On Order:")
display(
    inventory[inventory["On_Order"] < 0]
)


print("\nLead Time summary:")
display(inventory["Lead_Time_Days"].describe())

Shape: (4800, 8)

Duplicate SKU + Snapshot Date:
0

Negative Current Stock:

Empty DataFrame
Columns: [Snapshot_Date, SKU, Current_Stock, On_Order, Lead_Time_Days, Safety_Stock, Reorder_Point, Inventory_Value]
Index: []

Negative On Order:

Empty DataFrame
Columns: [Snapshot_Date, SKU, Current_Stock, On_Order, Lead_Time_Days, Safety_Stock, Reorder_Point, Inventory_Value]
Index: []

Lead Time summary:

count    4800.000000
mean        8.438958
std         3.488024
min         3.000000
25%         5.000000
50%         8.000000
75%        11.250000
max        14.000000
Name: Lead_Time_Days, dtype: float64

In [210]:
sales_skus = set(sales_daily["SKU"])
master_skus = set(sku_master["SKU"])

print("Sales SKUs not in SKU Master:")
print(sales_skus - master_skus)

Sales SKUs not in SKU Master:
set()

In [211]:
inventory_skus = set(inventory["SKU"])

print("Inventory SKUs not in SKU Master:")
print(inventory_skus - master_skus)

Inventory SKUs not in SKU Master:
{'SKU093', 'SKU196', 'SKU091', 'SKU133', 'SKU096', 'SKU157', 'SKU144', 'SKU111', 'SKU186', 'SKU118', 'SKU066', 'SKU166', 'SKU127', 'SKU052', 'SKU107', 'SKU121', 'SKU079', 'SKU102', 'SKU116', 'SKU074', 'SKU092', 'SKU098', 'SKU085', 'SKU179', 'SKU170', 'SKU090', 'SKU188', 'SKU095', 'SKU068', 'SKU175', 'SKU150', 'SKU185', 'SKU160', 'SKU145', 'SKU126', 'SKU099', 'SKU129', 'SKU140', 'SKU060', 'SKU097', 'SKU055', 'SKU077', 'SKU198', 'SKU128', 'SKU117', 'SKU200', 'SKU069', 'SKU138', 'SKU169', 'SKU192', 'SKU189', 'SKU119', 'SKU120', 'SKU064', 'SKU187', 'SKU104', 'SKU100', 'SKU086', 'SKU135', 'SKU197', 'SKU124', 'SKU081', 'SKU132', 'SKU054', 'SKU123', 'SKU191', 'SKU156', 'SKU171', 'SKU177', 'SKU062', 'SKU113', 'SKU051', 'SKU063', 'SKU105', 'SKU122', 'SKU182', 'SKU152', 'SKU151', 'SKU053', 'SKU190', 'SKU184', 'SKU112', 'SKU149', 'SKU109', 'SKU163', 'SKU058', 'SKU057', 'SKU130', 'SKU084', 'SKU183', 'SKU101', 'SKU114', 'SKU180', 'SKU142', 'SKU067', 'SKU065', 'SKU083', 'SKU194', 'SKU164', 'SKU106', 'SKU181', 'SKU082', 'SKU147', 'SKU153', 'SKU148', 'SKU146', 'SKU167', 'SKU076', 'SKU159', 'SKU125', 'SKU108', 'SKU137', 'SKU134', 'SKU178', 'SKU136', 'SKU075', 'SKU103', 'SKU110', 'SKU080', 'SKU162', 'SKU176', 'SKU195', 'SKU072', 'SKU088', 'SKU094', 'SKU059', 'SKU154', 'SKU089', 'SKU073', 'SKU070', 'SKU193', 'SKU139', 'SKU172', 'SKU056', 'SKU143', 'SKU131', 'SKU061', 'SKU168', 'SKU155', 'SKU115', 'SKU165', 'SKU071', 'SKU141', 'SKU199', 'SKU173', 'SKU078', 'SKU087', 'SKU158', 'SKU174', 'SKU161'}

In [212]:
# calendar["date"] = pd.to_datetime(calendar["date"])
# sales_daily["Date"] = pd.to_datetime(sales_daily["Date"])
# inventory["Snapshot_Date"] = pd.to_datetime(inventory["Snapshot_Date"])
# sku_master["Launch_Date"] = pd.to_datetime(sku_master["Launch_Date"])

In [213]:
sku_master["Launch_Date"] = pd.to_datetime(
    sku_master["Launch_Date"]
)

calendar["date"] = pd.to_datetime(
    calendar["date"]
)

inventory["Snapshot_Date"] = pd.to_datetime(
    inventory["Snapshot_Date"]
)

sales_daily["Date"] = pd.to_datetime(
    sales_daily["Date"]
)

In [214]:
print("Sales:", sales_daily["Date"].min(), "→", sales_daily["Date"].max())

print("Calendar:", calendar["date"].min(), "→", calendar["date"].max())

print("Inventory:", inventory["Snapshot_Date"].min(), "→", inventory["Snapshot_Date"].max())

Sales: 2024-01-01 00:00:00 → 2025-12-31 00:00:00
Calendar: 2024-01-01 00:00:00 → 2025-12-31 00:00:00
Inventory: 2024-01-01 00:00:00 → 2025-12-01 00:00:00

In [215]:
sales_dates = set(sales_daily["Date"])
calendar_dates = set(calendar["date"])

missing_calendar_dates = sales_dates - calendar_dates

print("Number of sales dates missing from calendar:")
print(len(missing_calendar_dates))

print("\nMissing dates:")
print(sorted(missing_calendar_dates)[:20])

Number of sales dates missing from calendar:
0

Missing dates:
[]

In [216]:
sales_daily["Calculated_Revenue"] = (
    sales_daily["Units_Sold"] * sales_daily["Price"]
)

sales_daily["Revenue_Difference"] = (
    sales_daily["Revenue"]
    - sales_daily["Calculated_Revenue"]
)

display(
    sales_daily[
        sales_daily["Revenue_Difference"].abs() > 0.01
    ].head(20)
)

Empty DataFrame
Columns: [Date, SKU, Units_Sold, Revenue, Price, Promotion, Calculated_Revenue, Revenue_Difference]
Index: []

### Generating a compact dataset summary

In [195]:
summary = pd.DataFrame({
    "Dataset": [
        "SKU Master",
        "Sales Daily",
        "Calendar",
        "Inventory"
    ],
    "Rows": [
        sku_master.shape[0],
        sales_daily.shape[0],
        calendar.shape[0],
        inventory.shape[0]
    ],
    "Columns": [
        sku_master.shape[1],
        sales_daily.shape[1],
        calendar.shape[1],
        inventory.shape[1]
    ],
    "Missing Values": [
        sku_master.isnull().sum().sum(),
        sales_daily.isnull().sum().sum(),
        calendar.isnull().sum().sum(),
        inventory.isnull().sum().sum()
    ]
})

display(summary)

       Dataset   Rows  Columns  Missing Values
0   SKU Master     50        8               0
1  Sales Daily  36550        8               0
2     Calendar    731       11            1379
3    Inventory   4800        8               0

### Sales → SKU Master

In [217]:
sales_not_in_master = set(sales_daily["SKU"]) - set(sku_master["SKU"])

print("Sales SKUs missing from SKU Master:", len(sales_not_in_master))
print(sales_not_in_master)

Sales SKUs missing from SKU Master: 0
set()

### Inventory → SKU Master

In [218]:
inventory_not_in_master = set(inventory["SKU"]) - set(sku_master["SKU"])

print("Inventory SKUs missing from SKU Master:", len(inventory_not_in_master))
print(inventory_not_in_master)

Inventory SKUs missing from SKU Master: 150
{'SKU093', 'SKU196', 'SKU091', 'SKU133', 'SKU096', 'SKU157', 'SKU144', 'SKU111', 'SKU186', 'SKU118', 'SKU066', 'SKU166', 'SKU127', 'SKU052', 'SKU107', 'SKU121', 'SKU079', 'SKU102', 'SKU116', 'SKU074', 'SKU092', 'SKU098', 'SKU085', 'SKU179', 'SKU170', 'SKU090', 'SKU188', 'SKU095', 'SKU068', 'SKU175', 'SKU150', 'SKU185', 'SKU160', 'SKU145', 'SKU126', 'SKU099', 'SKU129', 'SKU140', 'SKU060', 'SKU097', 'SKU055', 'SKU077', 'SKU198', 'SKU128', 'SKU117', 'SKU200', 'SKU069', 'SKU138', 'SKU169', 'SKU192', 'SKU189', 'SKU119', 'SKU120', 'SKU064', 'SKU187', 'SKU104', 'SKU100', 'SKU086', 'SKU135', 'SKU197', 'SKU124', 'SKU081', 'SKU132', 'SKU054', 'SKU123', 'SKU191', 'SKU156', 'SKU171', 'SKU177', 'SKU062', 'SKU113', 'SKU051', 'SKU063', 'SKU105', 'SKU122', 'SKU182', 'SKU152', 'SKU151', 'SKU053', 'SKU190', 'SKU184', 'SKU112', 'SKU149', 'SKU109', 'SKU163', 'SKU058', 'SKU057', 'SKU130', 'SKU084', 'SKU183', 'SKU101', 'SKU114', 'SKU180', 'SKU142', 'SKU067', 'SKU065', 'SKU083', 'SKU194', 'SKU164', 'SKU106', 'SKU181', 'SKU082', 'SKU147', 'SKU153', 'SKU148', 'SKU146', 'SKU167', 'SKU076', 'SKU159', 'SKU125', 'SKU108', 'SKU137', 'SKU134', 'SKU178', 'SKU136', 'SKU075', 'SKU103', 'SKU110', 'SKU080', 'SKU162', 'SKU176', 'SKU195', 'SKU072', 'SKU088', 'SKU094', 'SKU059', 'SKU154', 'SKU089', 'SKU073', 'SKU070', 'SKU193', 'SKU139', 'SKU172', 'SKU056', 'SKU143', 'SKU131', 'SKU061', 'SKU168', 'SKU155', 'SKU115', 'SKU165', 'SKU071', 'SKU141', 'SKU199', 'SKU173', 'SKU078', 'SKU087', 'SKU158', 'SKU174', 'SKU161'}

### Sales → Calendar

In [219]:
sales_dates = set(sales_daily["Date"])
calendar_dates = set(calendar["date"])

missing_dates = sales_dates - calendar_dates

print("Sales dates missing from Calendar:", len(missing_dates))
print(sorted(missing_dates)[:20])

Sales dates missing from Calendar: 0
[]